name: delete-github-action-caches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@5f305e3ee1b681c44328cdf11eaedf943b60edff # Commit #11 in main, from 6 may 2024
